//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaystackSampleWebApp.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public long OrderId { get; set; }
        public string OrderReference { get; set; }
        public string Surname { get; set; }
        public string Othername { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string PaymentReference { get; set; }
    }
}
